name: Build Android APK

on: [push, workflow_dispatch]

env:
  ANDROID_HOME: /usr/local/lib/android/sdk
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            git unzip openjdk-17-jdk \
            zlib1g-dev libncurses5-dev \
            libsqlite3-dev libffi-dev \
            libbz2-dev liblzma-dev

    - name: Setup Android SDK and NDK
      run: |
        # Descargar command-line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        
        # Crear estructura de directorios correcta
        mkdir -p $ANDROID_HOME/cmdline-tools
        unzip commandlinetools-linux-*.zip -d cmdline-tools-temp
        mv cmdline-tools-temp/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        rm -rf cmdline-tools-temp *.zip

        # Configurar entorno
        echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
        
        # Aceptar licencias
        yes | sdkmanager --licenses
        
        # Instalar componentes esenciales
        sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34" "ndk;26.1.10909125"

        # Verificar instalación
        echo "Android SDK tools:"
        ls $ANDROID_HOME/cmdline-tools/latest/bin
        echo "Android NDK:"
        ls $ANDROID_HOME/ndk

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        buildozer -v android clean
        buildozer -v android debug
        ls -lh ./bin

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: App-APK
        path: ./bin/*.apk
        if-no-files-found: error
